export enum paths {
  ROOT = "/",
  HOME = "/home",
  CONTACT = "/contact-us",
  COUNTRY = "/country",
  ABOUTUS = "/aboutus",
  OURSERVICES = "/ourservices",
  STUDYVISA = "/studyvisa",
  CAREHOMEVISA = "/carehomevisa",
  COMMUNICATIONTRAINING = "/communicationtraining",
  IELTS = "/ielts",
  TOEFL = "/toefl",
  PTE = "/pte",
  DUOLINGO = "/duolingo",
  OET = "/oet",
  INTERVIEWTRAINING = "/interviewtraining",
  ACADEMICGUIDANCE = "/academicguidance",
  JOBGUIDANCE = "/jobguidance",
  MANPOWER = "/manpowerservice",
  NEWSANDUPDATES = "/newsandupdates",
}
